### ISSUE TITLE
Solving Magento Enterprise edition/.NET integration rest

### ISSUE THREAD

**Issue by 78fede78** [nickvane/Magento-RestApi#11]
I'm trying to make a request HTTP from .NET to Magento 1.8 Enterprise edition, 
but apparently I don't have any response.

OAuth Authentication is working and reply also correct token

Dou you have any suggestion to resolve this problem?

Any idea why I don't receive a response?

Here following the code I'm using: 

```
var client = new MagentoApi().Initialize("http://test.xxxxxxxxx.nl", "xxxxxxxxxxxxxxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx").AuthenticateAdmin("xxx", "xxxxxxx");
var response = client.GetProductById(1).Result;


I tried to debug your code but it stops here:

  var response = await Client.ExecuteTaskAsync(request);
```

Can you please help me out?
Thank you 
Regards

**Comment by carlosptt** [comment]
Hi, a have a problem

I need, get to cateries description whit API REST

please Help

I used Magento 1.9
