### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by evapeak** [nickvane/Magento-RestApi#14]
Not an issue, but might be helpful for others.  Spent all morning on this!  I was getting an exception that "soap-admin" was not a Magento admin.

After using fildler, I worked out that Captcha was block it.  Seems this does a post to the Admin login form, instead of a "real" api.

**Comment by nickvane** [comment]
Thank you for the feedback!

**Comment by rizwanqur** [comment]
how to handle captcha in code? when initialization?
