### ISSUE TITLE
Missing fields when not publicly documented

### ISSUE THREAD

**Issue by vermorel** [nickvane/Magento-RestApi#15]
The Magento REST documentation omit many important fields. For example, the `Order` comes with a `created_at` field (without this field, sales orders are not dated) which is returned by Magento, probably since v1.7, but still undocumented.

It seems that the `Magento-RestApi` is missing most of those undocumented fields. It would be a very nice addition to review the classes to add the missing bits. Just listing a few:

* `Order.created_at`
* `Order.remote_ip`
* `Order.store_currency_code`
* `Order.store_name`

**Comment by nickvane** [comment]
If you can list them, I'll add them.

**Comment by vermorel** [comment]
Thanks! The one that I have listed above are the one I did identify so far. ` created_at` is a `DateTime`, all the others are `string`.

**Comment by vermorel** [comment]
A couple more fields:

* `OrderItem.item_id`
* `OrderItem.parent_item_id`
* `OrderItem.sku`
* `OrderItem.name`
* `OrderItem.qty_canceled`
* `OrderItem.qty_invoiced`
* `OrderItem.qty_ordered`
* `OrderItem.qty_refunded`
* `OrderItem.qty_shipped`

**Comment by nickvane** [comment]
Hi. I have made an update and added all missing fields from order, orderitem and also added order comments. It is version 1.0.1 on nuget.
I tested this against a live Magento installation, but only with 2 orders. If something should fail, let me know.
