### ISSUE TITLE
Issue like i hve get message "MethodNotAllowed" when create,update or delete any entity like product

### ISSUE THREAD

**Issue by Rakesh-Magento** [nickvane/Magento-RestApi#18]
i have integrate magento rest api into my .net application. it is working like get data from magento store but i have update any information on magento store that time get message "MethodNotAllowed" in response, so please help me any configuration is remainng or needed any chages in magento admin side. i have already dome all required things. so please support me on that...

**Comment by nickvane** [comment]
It looks like you have either:
- not configured all roles and permissions for an admin user correctly (http://www.magentocommerce.com/api/rest/permission_settings/roles_configuration.html)
- or you are not logging in with a user that is not an admin
- or the resource access for that rest role is not enabled for all resources

If you can login via the library, then it is certainly some REST resource configuration in Magento. The link I provided you should give you enough information.
