### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by RamonMarkets** [nickvane/Magento-RestApi#19]
Good day,

I'm getting the following error when trying to use the AuthenticateAdmin("username", "password"); function:

Method not found: 'Void RestSharp.RestClient.set_Authenticator(RestSharp.|Authenticator)'

Please help, I've been trying to get it to work but fail to find a solution.

Using Magento ver. 1.9.0.1

**Comment by nickvane** [comment]
Are you using the library from the nuget package (1.0.1 = latest) or have you build it from source?
Make sure you have the correct corresponding RestSharp version. For the version on NuGet, the restsharp version should be: ≥ 105.1.0
I think a different version of restsharp is being used that doesn't have the property, or property setter for Authenticator.

**Comment by RamonMarkets** [comment]
I'm using the library from the Nuget Package 1.0.1 and RestSharp 105.2.2 is installed. Here is the list of packages installed:

<packages>
  <package id="HtmlAgilityPack" version="1.4.9" targetFramework="net452" />
  <package id="Magento.RestApi" version="1.0.1" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="7.0.1" targetFramework="net452" />
  <package id="RestSharp" version="105.2.2" targetFramework="net452" />
</packages>

**Comment by nickvane** [comment]
Ok. Just reproduced it. It's the RestSharp version bump. Works with 105.1.0, but not with 105.2.2.
If you can downgrade to 105.1.0, you will be fine for now. I'll figure out what has changed in this minor upgrade that breaks oauth authentication in RestSharp.

**Comment by nickvane** [comment]
Apparently the contrib namespace in RestSharp was renamed in between those versions.
I updated to latest version of RestSharp and pushed a new nuget package (1.0.2)

**Comment by RamonMarkets** [comment]
Awesome. Problem fixed. Thanks so much.
