### ISSUE TITLE
Oauth Callback URL

### ISSUE THREAD

**Issue by RamonMarkets** [nickvane/Magento-RestApi#20]
Hi,

How can I change the oauth_callback. The default oauth_callback (http://localhost:8888) is causing authorization problems. I've tested the URL being sent to authorize the admin user in postman but manually change the oauth_callback and gotten the correct response, which is the oauth_token and oauth_token_secret. Otherwise I just get an error 400.

Your help would be greatly appreciated.

**Comment by nickvane** [comment]
Hi Ramon,

Added possibility to change oauth callback url in version 1.0.3 on nuget.
See readme.md for usage.
