### ISSUE TITLE
If order_comments.is_customer_notified is null, throws an exception

### ISSUE THREAD

**Issue by 75559** [nickvane/Magento-RestApi#21]
Hello,

I'm having an exception trying to get all orders.

Here is the inner exception of type {System.Collections.ListDictionaryInternal}:
"Error converting value {null} to type 'System.Int32'. Path '7.order_comments[2].is_customer_notified', line 1, position 25252."

Apparently, solution would be to change type of field is_customer_notified to int? or to add an Int32 JsonConverter.

Thanks,

**Comment by gajvries** [comment]
Hello,

I am having the same blocking issue.
is_customer_notified can be null.

If you need a test server just let me know.

**Comment by nickvane** [comment]
Hi,

Changed to nullable type in version 1.0.3 on nuget.
I haven't tested the order implementation on my side, so there still might be some issues.
Let me know if you bump into anything else.
