### ISSUE TITLE
Cannot convert string to int for increment_id on edited orders

### ISSUE THREAD

**Issue by martinberglund** [nickvane/Magento-RestApi#23]
When order is edited from the admin page the order is recreated as a new childorder with a order ID with a dash (100000003-1). This throws an exception.

Inner exception i get is: "{"Could not convert string to integer: 100000003-1. Path '4.increment_id', line 1, position 9103."}"

Magento version: 1.9.2.1
Magento-RestApi installed from NuGet package

**Comment by nickvane** [comment]
Hi Martin,

Changed to type string and is available in nuget in version 1.0.3
