### ISSUE TITLE
Issue with different URL for OAuth and api

### ISSUE THREAD

**Issue by receter** [nickvane/Magento-RestApi#25]
I have a magneto store that uses StoreCodes in the the URL. eg. http://magentostore.com/en/

With this setting my oauth and and api urls are:

 http://magentostore.com/en/oauth/...
 http://magentostore.com/api/rest/...

If I call .Initialize("http://magentostore.com", ... your Library assumes that the urls are:

 http://magentostore.com/oauth/...
 http://magentostore.com/api/rest/...

If I use the Url with StoreCode (.Initialize("http://magentostore.com/en", ...) your Library assumes that the urls are:

 http://magentostore.com/en/oauth/...
 http://magentostore.com/en/api/rest/...

I it possible to set different URLs for oauth and api?

PS: Thank you for uploading your code to GitHub, I am really happy that I found your Library!

**Comment by receter** [comment]
I solved this Issue by adding this to the local config:

<config>
  [...]
  <global>
    [...] 
    <request>
        [...] 
        <direct_front_name>
            <oauth/>
        </direct_front_name>
    </request>
  </global>
</config>

http://stackoverflow.com/questions/14472228/magento-rest-api-oauth-url-returning-404

**Comment by davidzovko** [comment]
@receter could you please care to help me with the same issue as yours? 

I do have a local.xml file, but it does not include <requests> or >direct_front_name> tags. It this from app/etc/local.xml or some other place? 

Thank you a lot, appreciate it.

**Comment by receter** [comment]
Yeah I guess that was the file. Just add all missing node to the file and be sure to clear all caches.
