### ISSUE TITLE
Magento v 2.x

### ISSUE THREAD

**Issue by raver2046** [nickvane/Magento-RestApi#27]
Hello the path to the api has been moved in the v2 and i can't use this wonderfull component.

v2  :
http://ubuntu/magento/rest/v1/products?filter%5B0%5D%5Battribute%5D=sku&filter%5B0%5D%5Bin%5D=NS724847

and before : http://ubuntu/magento/api/rest/product

can you fix this?

**Comment by nickvane** [comment]
Magento v2 is a complete rewrite of the REST API. This library would have to be rewritten also.
There is no way to use the current library for v2.
