### ISSUE TITLE
Magento 2

### ISSUE THREAD

**Issue by jmawebtech** [nickvane/Magento-RestApi#29]
Hi,

Does this library work with Magento 2? If so, what steps must I take to set-up Magento 2?

**Comment by nickvane** [comment]
No. Magento 2 has a much bigger REST API and this library would have to be rewritten entirely to address this. I've briefly looked into how it could be done, but don't have any plans yet

**Comment by alexishughes** [comment]
Do you have a commercial product that does work on M2.3?
