### ISSUE TITLE
Custom Attributes when Creating a new product

### ISSUE THREAD

**Issue by gg3orgiev** [nickvane/Magento-RestApi#30]
Hi,

How can I create a new product with custom attributes, created in magento.
For example I would like to create a product which has 2 custom required attributes (beside the default ones). 

Regards,
Georgi

**Comment by nickvane** [comment]
You'll use the attributes property on product for that.

    var product = new Product();
    product.attributes.Add("CustomAttributeName1", "Value");
    product.attributes.Add("CustomAttributeName2", "Value");

**Comment by gg3orgiev** [comment]
Thought so, but when I add the attributes that way, I recieve

An unhandled exception of type* 'System.AggregateException' occurred in
mscorlib.dll *
with *Inner Exception:*
{"Object reference not set to an instance of an object."}
and *Stack Trace: *
   at Magento.RestApi.Json.ProductConverter.WriteJson(JsonWriter writer,
Object value, JsonSerializer serializer)
   at
Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter
writer, JsonConverter converter, Object value, JsonContract contract,
JsonContainerContract collectionContract, JsonProperty containerProperty)
   at
Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter
writer, Object value, JsonContract valueContract, JsonProperty member,
JsonContainerContract containerContract, JsonProperty containerProperty)
   at
Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter
jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter
jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value,
Type type, JsonSerializer jsonSerializer)
   at Magento.RestApi.Json.JsonSerializer.Serialize(Object obj)
   at RestSharp.RestRequest.AddBody(Object obj, String xmlNamespace)
   at RestSharp.RestRequest.AddBody(Object obj)
   at Magento.RestApi.MagentoApi.<CreateNewProduct>d__38.MoveNext()

Do you have any idea why I get that exception ?

**Comment by runin2k1** [comment]
Probably too late for you gg3orgiev, but this will get you past the serialization error:

    var product = new Product();
    product.Attributes = new Dictionary<string, string>();
    
    // retrieve our attributes as a Property to enable change tracking fields
    var attributes = product.GetProperty(p => p.Attributes);
    
    // initialize inital value to prevent null pointer exception
    attributes .SetValueAsInitial();
    
    // add custom attributes
    attributes.Add("CustomAttributeName1", "Value");
    attributes.Add("CustomAttributeName2", "Value");

And here's the line that fails in ProductConverter.cs due to InitialValue being null when you initialize product.Attributes to a plain Dictionary... 

    if (!attributes.InitialValue.ContainsKey(attribute.Key)) : line 95

This should probably be handled automatically in the Product constructor or StartTracking method but I'm not 100% certain without diving a bit deeper.

**Comment by klauszhang** [comment]
@runin2k1 You saved my day! Thank you!
