### ISSUE TITLE
Product attribute doesn't send - error Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by pr0lame** [nickvane/Magento-RestApi#31]
Hi, 
I have a problem with sending product attributes.
Error when sending -
But when I send the product without attributes, it passes without errors.
Attributes are not required in Magento, are assigned in such a way:
http://i.imgur.com/LGYcuwQ.png

Any solution or example to send attributes in C #?

**Comment by pcanale52** [comment]
Crazy - I just came across this problem myself.
http://i.imgur.com/nHOS3yF.png

Any help would be appreciated...thanks!

**Comment by pr0lame** [comment]
Hi nickvane,

This way still not pass data: 
http://i.imgur.com/r7DrAl7.png

**Comment by pcanale52** [comment]
pr0lame, this code is working for me:

http://i.imgur.com/PcVIheB.png

**Comment by gg3orgiev** [comment]
Any updates on this issue?

**Comment by nickvane** [comment]
This should be fixed in the latest update 1.0.4
The HasChanged method didn't handle the Dictionary correctly.
