### ISSUE TITLE
Serialization issue getting images for product with custom image type

### ISSUE THREAD

**Issue by codelabnz** [nickvane/Magento-RestApi#35]
Hi, 

Our client has a image type called Rotator Image (I assume this is a custom image type based on a extension) and I get an JSON serialization exception raised when trying to load images for a product using the following call ```client.GetImagesForProduct```.

Exception is:

Newtonsoft.Json.JsonSerializationException
Message = "Requested value 'rotator_image' was not found."
Error converting value "rotator_image" to type 'Magento.RestApi.Models.ImageType'. Path 'types[0]', line 1, position 172.

**Comment by nickvane** [comment]
I added the type to the enumerator in the latest version 1.0.4
