### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by Bleus** [nickvane/Magento-RestApi#45]
In the event that the target Magento implementation includes add-ons that create custom fields, is there any way to access those fields through this API? 

For example, amongst several others, the implementation I'm tasked with addressing includes an add-on that adds a field to all order records (which has been named "QuickbooksSR") so they can be tagged with the corresponding QuickBooks Sales-Receipt (or Invoice) Number for ease of cross-reference. I need to be able to read and write this field from the C# client (which is being written to accesses both QuickBooks and Magento data through a single user interface).

**Comment by Bleus** [comment]
FWIW, the extra fields are created / managed through this add-on:
http://amasty.com/order-memos-and-attachments.html

**Comment by Bleus** [comment]
Okay, well I've finally had a discussion with the developer of this add-on and have been informed that it is not compatible with REST, so I'm fairly certain that will pretty deftly preclude it from being accessed with this API...

**Comment by nickvane** [comment]
Custom fields are added to a dictionary property called Attributes.
