### ISSUE TITLE
oauth signature invalid when using wildcard filters in queries

### ISSUE THREAD

**Issue by micah8719** [nickvane/Magento-RestApi#8]
I'm not sure if this is an issue with Magento, RestSharp, or Magento-RestApi. I stepped through the code and then stepped through session in Fiddler, but didn't notice anything out of the ordinary with the initial request.

I added a filter field operator to my local branch called "like". I can confirm that the filter is valid (even though Magento doesn't mention it) because setting a fieldValue = "sometex_" (using the one character wildcard), it returns the correct value in the response. If I set fieldValue = "somet%", I get an error response back saying that the oauth signature is invalid.

For some reason, it doesn't like that % sign being in there. I've tried escaping it, I've tried using %25 instead, neither of which are working for some reason. I first suspected it being a query sanitization issue with Magento, but I know filter using a "like" while using the SOAP API works correctly.

**Comment by nickvane** [comment]
Looks like with upgrading to the latest RestSharp package the issue is solved.
Commit b672b96ff9b54a7fc784ff16a860729b4368046a
I used:

    filter.FilterExpressions.Add(new FilterExpression("name", ExpressionOperator.like, "Melting%"));

and that returned a product in my test environment. I also added it to the integration tests.
