### ISSUE TITLE
"Resource collection filtering error."

### ISSUE THREAD

**Issue by auspex-nl** [nickvane/Magento-RestApi#9]
Whatever search for products or orders I try, I always get this response from the Mangeto REST API:

```
"{\"messages\":{\"error\":[{\"code\":400,\"message\":\"Resource collection filtering error.\"}]}}"
```

Happens for example when executing this:

```
            client.GetProductBySku("226bw").ContinueWith(t =>
            {
                if (!t.Result.HasErrors)
                {
                    var product = t.Result.Result;
                }
            });
```

I tried accessing the method synchronously by using client.GetProductsBySku("226bw").Result but that just hangs?

**Comment by ecin1resp1** [comment]
I am using the latest and I am getting this same error.

**Comment by InsomniumBR** [comment]
@ecin1resp1 @auspex-nl, 

Check that System => Web Service => REST Attributes was configured for your user.
This worked for me.

Source: https://github.com/nickvane/Magento-RestApi/issues/36
